### PR TITLE
openai: Support for Images in Message

### PR DESCRIPTION
**Pull request by Sushmithamallesh**
Issue link #6

### CODE REVIEW

**Comment by Sushmithamallesh** [comment]
This is for OpenAI image format. I am bit confused by the way in how anthropic types are handled here. Because the request always seem to be `openai.ChatCompletionRequest` type even in anthropic.
Will add this support in a following PR probably.

**Comment by h0rv** [comment]
@Sushmithamallesh Thank you for the PR! This is a great addition. I made some small changes to bump the OpenAI pkg version to use the new GPT-4o model for this as it is a perfect use case in your example and fixed a bug that was not letting the example run.

As for the Anthropic support, I was planning basing the instructor API based on OpenAI's as it is by far the popular client for Go. So, for the messages API I just have a `ToAnthropicMessages` function that translates the OpenAI's Messages Request to Anthropic's.

This package is in early development so would love to here feedback on this approach. Thanks again!

**Comment by h0rv** [comment]
Going to merge this now. Anthropic support can come in another PR

**Comment by Sushmithamallesh** [comment]
> @Sushmithamallesh Thank you for the PR! This is a great addition. I made some small changes to bump the OpenAI pkg version to use the new GPT-4o model for this as it is a perfect use case in your example and fixed a bug that was not letting the example run.
> 
> As for the Anthropic support, I was planning basing the instructor API based on OpenAI's as it is by far the popular client for Go. So, for the messages API I just have a `ToAnthropicMessages` function that translates the OpenAI's Messages Request to Anthropic's.
> 
> This package is in early development so would love to here feedback on this approach. Thanks again!

After I took a closer look. I think that makes sense. I was a bit confused is all. 
I looked around in for more Issues I can work on and contribute. For context I have experience writing Go for an year and have worked with python and JS for close to 2 years. I am looking to contribute more to open source. Let me know if there is any features you have in the roadmap or any documentation you need help on. 
Thanks a lot @h0rv

**Comment by h0rv** [comment]
Great. I just opened a few issues for more things we want to see get added. Improving the docs and examples would be great, along with adding more clients so more people can starting using the package too.

We also have a `#golang` channel in the instructor discord to discuss development efforts: https://discord.gg/CV8sPM5k5Y

Thanks @Sushmithamallesh!

**Comment by Sushmithamallesh** [comment]
Tried to join the discord channel. But the invite seems to be expired! @h0rv 
Let me know if its a discord error on my end though.

**Comment by h0rv** [comment]
@Sushmithamallesh try this one https://discord.gg/stRcTS7C

**Comment by Sushmithamallesh** [comment]
I am in thanks!

**Pull request merged**
